Unrecognized property 'documentation' issue resolved by adding validation rules
failsafe-engineering/serverless-aws-apigateway-documentation pull request #7
Opened 2021-05-07 10:19 UTC by gordana16

The Serverless Framework has added http event validation since version 2.6.0 without including 'documentation' property. Plugin developers are encouraged to extend validation schema by adding validation rules for additional properties supported by plugin.

This PR resolves "Unrecognized property 'documentation'" triggered by serverless framework (since version 2.6.0) by adding JSON schema definition for 'documentation' property inside 'serverless-aws-plugin' constructor.

2021-05-28 15:27 UTC, ottopecz commented
Thanks for the PR... I'm looking at it.

2021-05-30 13:15 UTC, ottopecz commented
@gordana16 - Again. Thanks for the PR. Nice work. It's hard to review it though because you completely reformatted both files. Please keep the original indentations... That will create a clear diff...

2021-05-30 13:15 UTC, ottopecz requested changes
Thanks for the PR. Nice work. It's hard to review it though because you completely reformatted both files. Please keep the original indentations... That will create a clear diff...

2021-05-30 13:17 UTC, ottopecz commented
@gordana16 - Also please rebase your branch against the master of this repo. Thanks so much.

2021-06-02 00:09 UTC, gordana16 commented
@ottopecz
Thank you for taking the time to review my PR. I'd rebased my branch and fixed indentation before I noticed you'd sent me 'Change requested'. Could you please review the PR again?

2021-06-03 12:12 UTC, ottopecz reviewed
Awesome work... Actually we already have a ticket to solve the issue so your PR comes just in time.
The only thing thing is that the PR has some changes which it shouldn't... Please look at my comments...
Perhaps you rebased the branch against the master of your fork? I'm just guessing...
Can you take a look at your git history please. Perhaps it's an easy fix.

2021-06-03 12:12 UTC, ottopecz commented on package.json
> -  "version": "1.1.2",
I'm not sure why this change shows up... We already have this on master

2021-06-03 12:12 UTC, ottopecz commented on README.md
> -
I'm not sure why this change shows up... We already have this on master.

2021-06-03 12:12 UTC, ottopecz commented on src/index.js
> +                    type: 'multiple'
I'm not sure why this change shows up... We already have this on master.

2021-06-03 12:12 UTC, ottopecz commented on src/index.js
> +                  type: 'string'
I'm not sure why this change shows up... We already have this on master.

2021-06-03 21:10 UTC, ottopecz commented
@gordana16 - I reckon the easiest way just to update your fork and recreate the branch and the PR.

2021-06-03 23:12 UTC, gordana16 commented
> 
> 
> Awesome work... Actually we already have a ticket to solve the issue so your PR comes just in time.
> The only thing thing is that the PR has some changes which it shouldn't... Please look at my comments...
> Perhaps you rebased the branch against the master of your fork? I'm just guessing...
> Can you take a look at your git history please. Perhaps it's an easy fix.

2021-06-03 23:12 UTC, closed without merging

2021-06-03 23:13 UTC, gordana16 commented
I will start from scratch